apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: student-12-project # remember to change this!
  namespace: argocd
spec:
  description: A project for student-12 to play with # remember to change this!
  destinations:
    - name: in-cluster
      namespace: student-12 #remember to change this!
      server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: Role
  sourceRepos:
    - https://github.com/eficode-academy/argocd-katas.git
